### ISSUE TITLE
Uncaught TypeError: in_array(): Argument #2 ($haystack) must be of type array, null given.

### ISSUE THREAD

**Issue by olatechpro** [publishpress/PublishPress-Capabilities#513]
Here's the full error message

Here's the full error message

error details
================
```
An E_ERROR error was caused on line 122 of the /wp-content/plugins/capabilities-pro/includes-pro/features/metaboxes.php file. Error message: Uncaught TypeError: in_array(): Argument #2 ($haystack) must be of type array, null given in /wp-content/plugins/capabilities-pro/includes-pro/ features/metaboxes.php:122
Stack trace:
#0 /wp-content/plugins/capabilities-pro/includes-pro/features/metaboxes.php(122): in_array('post', NULL)
#1 /wp-includes/class-wp-hook.php(307): PublishPress\Capabilities\EditorFeaturesMetaboxes->fltElements(Array)
#2 /wp-includes/plugin.php(191): WP_Hook->apply_filters(Array, Array)
#3 /wp-content/plugins/capabilities-pro/includes/features/restrict-editor-features.php(214): apply_filters('pp_capabilities...', Array)
#4 /wp-content/plugins/capabilities-pro/includes/features/restrict-editor-features.php(342): PP_Capabilities_Post_Features::elementsLayoutClassic()
#5 /wp-content/plugins/capabilities-pro/includes/features/restrict-editor-features.php(236): PP_Capabilities_Post_Features::getElements(Array, Array)
#6 /wp-includes/class-wp-hook.php(307): PP_Capabilities_Post_Features::applyRestrictionsClassic('')
#7 /wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)
#8 /wp-includes/plugin.php(476): WP_Hook->do_action(Array)
#9 /wp-admin/admin-header.php(163): do_action('admin_head')
#10 /wp-admin/edit-form-advanced.php(425): require_once('/nas/content/li...')
#11 /wp-admin/post.php(206): require('/nas/content/li...')
#12 {main}
thrown
```

**Comment by olatechpro** [comment]
Pro Pr https://github.com/publishpress/PublishPress-Capabilities-Pro/pull/144
